controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    mecanum_omni_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_controller:
      type: joint_state_controller/JointStateController
      
      
mecanum_omni_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint","rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint","rear_right_wheel_joint"]
    write_op_modes: ["motor_controller"]

    wheel_separation : 0.305 # lx + ly
    wheels_per_side: 2
    wheel_radius: 0.04

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    open_loop: false #Always set to false
    enable_odom_tf: true

    cmd_vel_timeout: 500 # milliseconds
    publish_limited_velocity: false
    velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.4
    linear.x.min_velocity: -0.4
    linear.x.max_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
    
    linear.y.has_velocity_limits: true
    linear.y.has_acceleration_limits: false
    linear.y.has_jerk_limits: false
    linear.y.max_velocity: 0.4
    linear.y.min_velocity: -0.4
    linear.y.max_acceleration: 0.0
    linear.y.max_jerk: 0.0
    linear.y.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

